export type CatalogProduct = {
  name: string;
  category: string;
};

export const baseCatalog: CatalogProduct[] = [
  { name: "Aceite", category: "Alimentos" },
  { name: "Agua mineral", category: "Bebidas" },
  { name: "Ají", category: "Alimentos" },
  { name: "Alcohol gel", category: "Cuidado personal" },
  { name: "Arroz", category: "Alimentos" },
  { name: "Avena", category: "Alimentos" },
  { name: "Azúcar", category: "Alimentos" },
  { name: "Bolsas de basura", category: "Limpieza" },
  { name: "Café", category: "Bebidas" },
  { name: "Carne", category: "Alimentos" },
  { name: "Cebolla", category: "Alimentos" },
  { name: "Cepillo de dientes", category: "Cuidado personal" },
  { name: "Cerveza", category: "Bebidas" },
  { name: "Cloro", category: "Limpieza" },
  { name: "Crema corporal", category: "Cuidado personal" },
  { name: "Desodorante", category: "Cuidado personal" },
  { name: "Detergente", category: "Limpieza" },
  { name: "Esponjas", category: "Limpieza" },
  { name: "Fideos", category: "Alimentos" },
  { name: "Fósforos", category: "Hogar" },
  { name: "Frutas", category: "Alimentos" },
  { name: "Galletas", category: "Alimentos" },
  { name: "Gas", category: "Hogar" },
  { name: "Guantes de goma", category: "Limpieza" },
  { name: "Guantes de trabajo", category: "Ferretería" },
  { name: "Harina", category: "Alimentos" },
  { name: "Harina de maíz", category: "Alimentos" },
  { name: "Harina integral", category: "Alimentos" },
  { name: "Huevos", category: "Alimentos" },
  { name: "Jabón", category: "Cuidado personal" },
  { name: "Jabón de loza", category: "Limpieza" },
  { name: "Leche", category: "Alimentos" },
  { name: "Leche descremada", category: "Alimentos" },
  { name: "Leche sin lactosa", category: "Alimentos" },
  { name: "Limpiador de pisos", category: "Limpieza" },
  { name: "Mantequilla", category: "Alimentos" },
  { name: "Mascarillas", category: "Cuidado personal" },
  { name: "Papel absorbente", category: "Hogar" },
  { name: "Papel aluminio", category: "Hogar" },
  { name: "Papel higiénico", category: "Cuidado personal" },
  { name: "Pasta de dientes", category: "Cuidado personal" },
  { name: "Pilas", category: "Hogar" },
  { name: "Pollo", category: "Alimentos" },
  { name: "Protector solar", category: "Cuidado personal" },
  { name: "Queso", category: "Alimentos" },
  { name: "Sal", category: "Alimentos" },
  { name: "Servilletas", category: "Hogar" },
  { name: "Shampoo", category: "Cuidado personal" },
  { name: "Suavizante", category: "Limpieza" },
  { name: "Té", category: "Bebidas" },
  { name: "Toallas húmedas", category: "Cuidado personal" },
  { name: "Verduras", category: "Alimentos" },
  { name: "Vinagre", category: "Alimentos" },
  { name: "Yogur", category: "Alimentos" }
];
